<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Alireza Rezaei">

<title>Data Analysis with R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="final_files/libs/clipboard/clipboard.min.js"></script>
<script src="final_files/libs/quarto-html/quarto.js"></script>
<script src="final_files/libs/quarto-html/popper.min.js"></script>
<script src="final_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="final_files/libs/quarto-html/anchor.min.js"></script>
<link href="final_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="final_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="final_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="final_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="final_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Data Analysis with R</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Alireza Rezaei</p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="question" class="level1">
<h1>Question</h1>
<section id="what-factors-predict-whether-someone-believes-that-immigrants-make-the-country-a-worse-or-better-place-to-live" class="level3">
<h3 class="anchored" data-anchor-id="what-factors-predict-whether-someone-believes-that-immigrants-make-the-country-a-worse-or-better-place-to-live">What factors predict whether someone believes that immigrants make the country a worse or better place to live?</h3>
</section>
</section>
<section id="hypotheses" class="level1">
<h1>Hypotheses</h1>
<section id="h1" class="level3">
<h3 class="anchored" data-anchor-id="h1">- H1</h3>
<p>People with higher income levels (<code>hinctnta</code>) are more likely to believe that immigrants make the country a better place to live</p>
</section>
<section id="h2" class="level3">
<h3 class="anchored" data-anchor-id="h2">- H2</h3>
<p>People who report higher levels of happiness (<code>happy</code>) are more likely to believe that immigrants make the country a better place to live.</p>
</section>
<section id="h3" class="level3">
<h3 class="anchored" data-anchor-id="h3">- H3</h3>
<p>People with children (<code>chldhhe</code>) are more likely to believe that immigrants make the country a better place to live.</p>
</section>
<section id="h4" class="level3">
<h3 class="anchored" data-anchor-id="h4">- H4</h3>
<p>Younger people (<code>age</code>) are more likely to believe that immigrants make the country a better place to live.</p>
</section>
</section>
<section id="cleaning-data" class="level1">
<h1>Cleaning Data</h1>
<section id="reading-dataset" class="level3">
<h3 class="anchored" data-anchor-id="reading-dataset">- Reading Dataset</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_spss</span>(<span class="st">"dataset.sav"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>na_columns <span class="ot">&lt;-</span> <span class="fu">colSums</span>(<span class="fu">is.na</span>(df)) <span class="sc">==</span> <span class="fu">nrow</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="handling-na-values" class="level3">
<h3 class="anchored" data-anchor-id="handling-na-values">- Handling NA values</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Identify columns with all NA values</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>na_columns <span class="ot">&lt;-</span> <span class="fu">sapply</span>(df, <span class="cf">function</span>(x) <span class="fu">all</span>(<span class="fu">is.na</span>(x)))</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove columns with all NA values</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>df_clean <span class="ot">&lt;-</span> df[, <span class="sc">!</span>na_columns]</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the number of NA values in each column</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>na_items <span class="ot">&lt;-</span> <span class="fu">colSums</span>(<span class="fu">is.na</span>(df_clean))</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Identify columns with more than 75% NA observations</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>columns_to_remove <span class="ot">&lt;-</span> <span class="fu">names</span>(na_items[na_items <span class="sc">&gt;</span> <span class="dv">1875</span>])</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove columns with more than 1875 NA observations</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>df_clean <span class="ot">&lt;-</span> df_clean[, <span class="sc">!</span>(<span class="fu">names</span>(df_clean) <span class="sc">%in%</span> columns_to_remove)]</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Changing NA observations to median or empty string</span></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (col <span class="cf">in</span> <span class="fu">colnames</span>(df_clean)) {</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">is.numeric</span>(df_clean[[col]])) {</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>    df_clean[[col]][<span class="fu">is.na</span>(df_clean[[col]])] <span class="ot">&lt;-</span> <span class="fu">median</span>(df_clean[[col]], <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> <span class="cf">if</span> (<span class="fu">is.character</span>(df_clean[[col]])) {</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>    df_clean[[col]][<span class="fu">is.na</span>(df_clean[[col]])] <span class="ot">&lt;-</span> <span class="st">""</span></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="removing-unique-value-columns" class="level3">
<h3 class="anchored" data-anchor-id="removing-unique-value-columns">- Removing unique value columns</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Find columns with one unique value</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>single_value_columns <span class="ot">&lt;-</span> <span class="fu">sapply</span>(df_clean, <span class="cf">function</span>(x) <span class="fu">length</span>(<span class="fu">unique</span>(x)) <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove columns with one unique value</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>df_clean <span class="ot">&lt;-</span> df_clean[, <span class="sc">!</span>single_value_columns]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="removing-duplicated-rows" class="level3">
<h3 class="anchored" data-anchor-id="removing-duplicated-rows">- Removing duplicated rows</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove duplicate rows</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>df_clean <span class="ot">&lt;-</span> <span class="fu">distinct</span>(df_clean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="cloning-data" class="level3">
<h3 class="anchored" data-anchor-id="cloning-data">- Cloning Data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cloning Dataset</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>dataset <span class="ot">&lt;-</span> df_clean</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="normality-homogeneity-check" class="level1">
<h1>Normality &amp; Homogeneity Check</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Checking the normality and variance homogeneity of the 'imwbcnt' variable</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(dataset<span class="sc">$</span>imwbcnt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  dataset$imwbcnt
W = 0.95515, p-value &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bartlett.test</span>(imwbcnt <span class="sc">~</span> hinctnta, <span class="at">data =</span> dataset)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Bartlett test of homogeneity of variances

data:  imwbcnt by hinctnta
Bartlett's K-squared = 10.767, df = 9, p-value = 0.2921</code></pre>
</div>
</div>
<p>Since the p-value for Shapiro-Wilk normality test is very low, we would reject the null hypothesis. This suggests that ‘imwbcnt’ variable is not normally distributed. In this case, we should consider using non-parametric alternatives to the t-tests and ANOVA, as those tests assume normality. I used Wilcoxon and Kruskal-Wallis Test as my non-parametric tests but also I included t-test and ANOVA too to compare the results of them.</p>
</section>
<section id="plots" class="level1">
<h1>Plots</h1>
<section id="histogram-q-q-plot-of-imwbcnt" class="level3">
<h3 class="anchored" data-anchor-id="histogram-q-q-plot-of-imwbcnt">- Histogram &amp; Q-Q plot of ‘imwbcnt’</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Histogram</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(dataset<span class="sc">$</span>imwbcnt , <span class="at">main =</span> <span class="st">"Histogram of imwbcnt"</span>, <span class="at">xlab =</span> <span class="st">"imwbcnt"</span>, <span class="at">col =</span> <span class="st">"purple"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="final_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From the plot above we can see that most of the people believe that immigrants have no influence over the livability condition of the country. However, more people believe that immigrants make a country worse to live than better.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Q-Q plot</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(dataset<span class="sc">$</span>imwbcnt , <span class="at">main =</span> <span class="st">"Q-Q Plot of imwbcnt"</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(dataset<span class="sc">$</span>imwbcnt , <span class="at">col =</span> <span class="st">"orange"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="final_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="scatter-plot---relationship-between-happy-and-imwbcnt" class="level3">
<h3 class="anchored" data-anchor-id="scatter-plot---relationship-between-happy-and-imwbcnt">- Scatter Plot - Relationship between ‘happy’ and ‘imwbcnt’</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Scatter plot of 'happy' vs 'imwbcnt'</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dataset<span class="sc">$</span>happy, dataset<span class="sc">$</span>imwbcnt, <span class="at">xlab =</span> <span class="st">"Happiness"</span>, <span class="at">ylab =</span> <span class="st">"imwbcnt"</span>, <span class="at">main =</span> <span class="st">"Scatter Plot of Happiness vs. imwbcnt"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="final_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Since the data points roughly form a linear pattern, it indicates a positive correlation between the two variables. A positive correlation means that as “Happiness” increases, “imwbcnt” also tends to increase.</p>
</section>
<section id="bar-plot---frequency-or-distribution-of-hinctnta-chldhhe" class="level3">
<h3 class="anchored" data-anchor-id="bar-plot---frequency-or-distribution-of-hinctnta-chldhhe">- Bar Plot - Frequency or distribution of ‘hinctnta’, ‘chldhhe’</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Bar plot for 'hinctnta'</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(<span class="fu">table</span>(dataset<span class="sc">$</span>hinctnta), <span class="at">xlab =</span> <span class="st">"Income Level"</span>, <span class="at">ylab =</span> <span class="st">"Frequency"</span>, <span class="at">main =</span> <span class="st">"Bar Plot of Income Level"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="final_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>By observing the plot above we can say that most people are in the average income range</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Bar plot for 'chldhhe'</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(<span class="fu">table</span>(dataset<span class="sc">$</span>chldhhe), <span class="at">xlab =</span> <span class="st">"Children in Household"</span>, <span class="at">ylab =</span> <span class="st">"Frequency"</span>, <span class="at">main =</span> <span class="st">"Bar Plot of Children in Household"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="final_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>By observing the plot above we can see that the number of individuals with child is roughly twice of the ones without.</p>
</section>
</section>
<section id="mean-comparison" class="level1">
<h1>Mean Comparison</h1>
<section id="wilcoxon-rank-sum-test" class="level2">
<h2 class="anchored" data-anchor-id="wilcoxon-rank-sum-test">Wilcoxon Rank-Sum Test</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Wilcoxon rank-sum test for 'imwbcnt' with respect to 'chldhhe'</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(imwbcnt <span class="sc">~</span> chldhhe, <span class="at">data =</span> dataset)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon rank sum test with continuity correction

data:  imwbcnt by chldhhe
W = 633761, p-value = 0.01119
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a new grouping variable based on 'happy'</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>dataset<span class="sc">$</span>happy_group <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(dataset<span class="sc">$</span>happy <span class="sc">&lt;=</span> <span class="dv">5</span>, <span class="st">"Low Happiness"</span>, <span class="st">"High Happiness"</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform the Wilcoxon rank-sum test for 'imwbcnt' with respect to 'happy_group'</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(imwbcnt <span class="sc">~</span> happy_group, <span class="at">data =</span> dataset)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon rank sum test with continuity correction

data:  imwbcnt by happy_group
W = 366225, p-value = 1.671e-12
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a new grouping variable based on 'agea'</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>dataset<span class="sc">$</span>age_group <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(dataset<span class="sc">$</span>agea <span class="sc">&lt;=</span> <span class="dv">50</span>, <span class="st">"Under 50yrs"</span>, <span class="st">"Above 50yrs"</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Wilcoxon rank-sum test for 'imwbcnt' with respect to 'agea'</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(imwbcnt <span class="sc">~</span> age_group, <span class="at">data =</span> dataset)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon rank sum test with continuity correction

data:  imwbcnt by age_group
W = 751192, p-value = 0.1302
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a new grouping variable based on 'hinctnta'</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>dataset<span class="sc">$</span>income_group <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(dataset<span class="sc">$</span>hinctnta <span class="sc">&lt;=</span> <span class="dv">5</span>, <span class="st">"Average and below"</span>, <span class="st">"Above average"</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Wilcoxon rank-sum test for 'imwbcnt' with respect to 'hinctnta'</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(imwbcnt <span class="sc">~</span> income_group, <span class="at">data =</span> dataset)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon rank sum test with continuity correction

data:  imwbcnt by income_group
W = 718980, p-value = 0.1326
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
</div>
<section id="chldhhe" class="level3">
<h3 class="anchored" data-anchor-id="chldhhe">- chldhhe</h3>
<p>The p-value for the comparison of “imwbcnt” between groups with and without children is 0.01119. Since the p-value is less than the significance level (commonly set to 0.05), we can conclude that there is a statistically significant difference in “imwbcnt” between the two groups.</p>
</section>
<section id="happy" class="level3">
<h3 class="anchored" data-anchor-id="happy">- Happy</h3>
<p>The p-value for the comparison of “imwbcnt” between groups with low happiness and high happiness is very small (1.671e-12). Again, it is less than the significance level, indicating a highly significant difference in “imwbcnt” between the two happiness groups.</p>
</section>
<section id="age" class="level3">
<h3 class="anchored" data-anchor-id="age">- Age</h3>
<p>The p-value for the comparison of “imwbcnt” between the two age groups is 0.1302. In this case, the p-value is greater than the significance level (0.05), indicating that we do not have enough evidence to reject the null hypothesis, and there is no statistically significant difference in “imwbcnt” between the two age groups. So the age does not in play a role in the people’s opinion on the immigrants making the country a better or worst place.</p>
</section>
<section id="income" class="level3">
<h3 class="anchored" data-anchor-id="income">- Income</h3>
<p>The p-value for the comparison of “imwbcnt” between the two income groups is 0.1326, which is greater than the significance level. As with the age group, there is no statistically significant difference in “imwbcnt” between the two income groups.</p>
</section>
<section id="box-plot---distribution-of-imwbcnt-across-happy_group" class="level3">
<h3 class="anchored" data-anchor-id="box-plot---distribution-of-imwbcnt-across-happy_group">- Box Plot - Distribution of ‘imwbcnt’ across ‘happy_group’</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Box plot for 'imwbcnt' across 'happy_group'</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(imwbcnt <span class="sc">~</span> happy_group, <span class="at">data =</span> dataset, <span class="at">xlab =</span> <span class="st">"Happiness Group"</span>, <span class="at">ylab =</span> <span class="st">"imwbcnt"</span>, <span class="at">main =</span> <span class="st">"Box Plot of imwbcnt across Happiness Group"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="final_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Box plot for 'imwbcnt' across 'age'</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(imwbcnt <span class="sc">~</span> age_group, <span class="at">data =</span> dataset, <span class="at">xlab =</span> <span class="st">"Age Group"</span>, <span class="at">ylab =</span> <span class="st">"imwbcnt"</span>, <span class="at">main =</span> <span class="st">"Box Plot of imwbcnt across age Group"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="final_files/figure-html/unnamed-chunk-14-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Box plot for 'imwbcnt' across 'income'</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(imwbcnt <span class="sc">~</span> income_group, <span class="at">data =</span> dataset, <span class="at">xlab =</span> <span class="st">"Income Group"</span>, <span class="at">ylab =</span> <span class="st">"imwbcnt"</span>, <span class="at">main =</span> <span class="st">"Box Plot of imwbcnt across income Group"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="final_files/figure-html/unnamed-chunk-14-3.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Box plot for 'imwbcnt' across 'child'</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(imwbcnt <span class="sc">~</span> chldhhe, <span class="at">data =</span> dataset, <span class="at">xlab =</span> <span class="st">"with or without child"</span>, <span class="at">ylab =</span> <span class="st">"imwbcnt"</span>, <span class="at">main =</span> <span class="st">"Box Plot of imwbcnt across with or without children"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="final_files/figure-html/unnamed-chunk-14-4.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The horizontal line inside each box represents the median value of “imwbcnt” for each group. The height and width of the boxes show the interquartile range (IQR) of “imwbcnt” for each group. Individual points beyond the whiskers of the box plot are considered outliers.</p>
<ul>
<li>We can see that different level of happiness influences the view of people about my question</li>
<li>Same is appliable for individuals with children against those without children but not that significant.</li>
<li>As for age and income, we can see they are irrelevant to their view.</li>
</ul>
</section>
</section>
<section id="kruskal-wallis-test" class="level2">
<h2 class="anchored" data-anchor-id="kruskal-wallis-test">Kruskal-Wallis Test</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># kruskal test for 'imwbcnt' with respect to 'chldhhe'</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">kruskal.test</span>(imwbcnt <span class="sc">~</span> chldhhe, <span class="at">data =</span> dataset)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  imwbcnt by chldhhe
Kruskal-Wallis chi-squared = 6.4348, df = 1, p-value = 0.01119</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># kruskal test for 'imwbcnt' with respect to 'happy'</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">kruskal.test</span>(imwbcnt <span class="sc">~</span> happy, <span class="at">data =</span> dataset)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  imwbcnt by happy
Kruskal-Wallis chi-squared = 145.93, df = 10, p-value &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># kruskal test for 'imwbcnt' with respect to 'agea'</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">kruskal.test</span>(imwbcnt <span class="sc">~</span> agea, <span class="at">data =</span> dataset)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  imwbcnt by agea
Kruskal-Wallis chi-squared = 100.28, df = 75, p-value = 0.0273</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># kruskal test for 'imwbcnt' with respect to 'hinctnta'</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">kruskal.test</span>(imwbcnt <span class="sc">~</span> hinctnta, <span class="at">data =</span> dataset)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  imwbcnt by hinctnta
Kruskal-Wallis chi-squared = 24.614, df = 9, p-value = 0.003429</code></pre>
</div>
</div>
<section id="imwbcnt-by-chldhhe" class="level3">
<h3 class="anchored" data-anchor-id="imwbcnt-by-chldhhe">- imwbcnt by chldhhe</h3>
<ul>
<li>Kruskal-Wallis chi-squared: 6.4348</li>
<li>Degrees of freedom (df): 1</li>
<li>p-value: 0.01119 The p-value (0.01119) is less than the significance level (usually set to 0.05), which indicates that there is a significant difference in the distribution of “imwbcnt” among the different levels of the variable “chldhhe.” In other words, there is evidence to suggest that the median imwbcnt values are different between the two levels of “chldhhe.”</li>
</ul>
</section>
<section id="imwbcnt-by-happy" class="level3">
<h3 class="anchored" data-anchor-id="imwbcnt-by-happy">- imwbcnt by happy</h3>
<ul>
<li>Kruskal-Wallis chi-squared: 145.93</li>
<li>Degrees of freedom (df): 10</li>
<li>p-value: &lt; 2.2e-16 The p-value (&lt; 2.2e-16, which is very close to zero) is highly significant, indicating that there is a significant difference in the distribution of “imwbcnt” among the different levels of the variable “happy.” This means that the median imwbcnt values differ significantly across the ten levels of “happy.”</li>
</ul>
</section>
<section id="imwbcnt-by-agea" class="level3">
<h3 class="anchored" data-anchor-id="imwbcnt-by-agea">- imwbcnt by agea</h3>
<ul>
<li>Kruskal-Wallis chi-squared: 100.28</li>
<li>Degrees of freedom (df): 75</li>
<li>p-value: 0.0273 The p-value (0.0273) is less than 0.05, suggesting a significant difference in the distribution of “imwbcnt” among the different levels of the variable “agea.” Therefore, the median imwbcnt values are different across the age groups.</li>
</ul>
</section>
<section id="imwbcnt-by-hinctnta" class="level3">
<h3 class="anchored" data-anchor-id="imwbcnt-by-hinctnta">- imwbcnt by hinctnta</h3>
<ul>
<li>Kruskal-Wallis chi-squared: 24.614</li>
<li>Degrees of freedom (df): 9</li>
<li>p-value: 0.003429 The p-value (0.003429) is less than 0.05, indicating a significant difference in the distribution of “imwbcnt” among the different levels of the variable “hinctnta.” This means that the median imwbcnt values are different between the income groups.</li>
</ul>
</section>
</section>
<section id="t-test" class="level2">
<h2 class="anchored" data-anchor-id="t-test">(t-test)</h2>
<section id="imwbcnt-hinctnta" class="level3">
<h3 class="anchored" data-anchor-id="imwbcnt-hinctnta">imwbcnt &amp; hinctnta</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Subset the data </span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>group_positive_belief <span class="ot">&lt;-</span> <span class="fu">subset</span>(dataset, imwbcnt <span class="sc">&gt;</span> <span class="dv">6</span>)<span class="sc">$</span>hinctnta</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>group_negative_belief <span class="ot">&lt;-</span> <span class="fu">subset</span>(dataset, imwbcnt <span class="sc">&lt;=</span> <span class="dv">6</span>)<span class="sc">$</span>hinctnta</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Run the t-test</span></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(group_positive_belief, group_negative_belief)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  group_positive_belief and group_negative_belief
t = -1.2541, df = 540.35, p-value = 0.2103
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -0.42275538  0.09329098
sample estimates:
mean of x mean of y 
 4.825758  4.990490 </code></pre>
</div>
</div>
<p>The p-value (0.2103) is greater than the significance level (usually set to 0.05), which indicates that there is not enough evidence to reject the null hypothesis. The null hypothesis states that there is no difference in the means of the two groups. Therefore, based on the p-value, we do not have sufficient evidence to conclude that there is a significant difference in means between group_positive_belief and group_negative_belief.</p>
</section>
<section id="imwbcnt-happy" class="level3">
<h3 class="anchored" data-anchor-id="imwbcnt-happy">imwbcnt &amp; happy</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Subset the data </span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>group_positive_belief <span class="ot">&lt;-</span> <span class="fu">subset</span>(dataset, imwbcnt <span class="sc">&gt;</span> <span class="dv">6</span>)<span class="sc">$</span>happy</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>group_negative_belief <span class="ot">&lt;-</span> <span class="fu">subset</span>(dataset, imwbcnt <span class="sc">&lt;=</span> <span class="dv">6</span>)<span class="sc">$</span>happy</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Run the t-test</span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(group_positive_belief, group_negative_belief)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  group_positive_belief and group_negative_belief
t = 8.7637, df = 601.29, p-value &lt; 2.2e-16
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 0.5700058 0.8992661
sample estimates:
mean of x mean of y 
 8.414141  7.679505 </code></pre>
</div>
</div>
<p>The p-value (&lt; 2.2e-16) is extremely small, much smaller than the usual significance level of 0.05. This indicates strong evidence against the null hypothesis. The null hypothesis states that there is no difference in the means of the two groups. With such a small p-value, we can safely reject the null hypothesis and conclude that there is a significant difference in means between group_positive_belief and group_negative_belief.</p>
</section>
<section id="imwbcnt-chldhhe" class="level3">
<h3 class="anchored" data-anchor-id="imwbcnt-chldhhe">imwbcnt &amp; chldhhe</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Subset the data </span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>group_positive_belief <span class="ot">&lt;-</span> <span class="fu">subset</span>(dataset, imwbcnt <span class="sc">&gt;</span> <span class="dv">6</span>)<span class="sc">$</span>chldhhe</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>group_negative_belief <span class="ot">&lt;-</span> <span class="fu">subset</span>(dataset, imwbcnt <span class="sc">&lt;=</span> <span class="dv">6</span>)<span class="sc">$</span>chldhhe</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Run the t-test</span></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(group_positive_belief, group_negative_belief)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  group_positive_belief and group_negative_belief
t = 3.6849, df = 533.27, p-value = 0.0002522
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 0.04575189 0.15023076
sample estimates:
mean of x mean of y 
 1.398990  1.300999 </code></pre>
</div>
</div>
<p>The p-value (0.0002522) is very small, indicating strong evidence against the null hypothesis. The null hypothesis states that there is no difference in the means of the two groups. With such a small p-value, we can reject the null hypothesis and conclude that there is a significant difference in means between group_positive_belief and group_negative_belief.</p>
</section>
<section id="imwbcnt-agea" class="level3">
<h3 class="anchored" data-anchor-id="imwbcnt-agea">imwbcnt &amp; agea</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Subset the data </span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>group_positive_belief <span class="ot">&lt;-</span> <span class="fu">subset</span>(dataset, imwbcnt <span class="sc">&gt;</span> <span class="dv">6</span>)<span class="sc">$</span>agea</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>group_negative_belief <span class="ot">&lt;-</span> <span class="fu">subset</span>(dataset, imwbcnt <span class="sc">&lt;=</span> <span class="dv">6</span>)<span class="sc">$</span>agea</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Run the t-test</span></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(group_positive_belief, group_negative_belief)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  group_positive_belief and group_negative_belief
t = -6.4225, df = 558.08, p-value = 2.871e-10
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -8.142667 -4.328550
sample estimates:
mean of x mean of y 
 46.31313  52.54874 </code></pre>
</div>
</div>
<p>The p-value (2.871e-10) is extremely small, indicating strong evidence against the null hypothesis. The null hypothesis states that there is no difference in the means of the two groups. With such a small p-value, we can reject the null hypothesis and conclude that there is a significant difference in means between group_positive_belief and group_negative_belief.</p>
<p><span style="color: red;">We can see that t-test shows opposite results comparing to our non-parametric methods</span></p>
</section>
</section>
</section>
<section id="one-way-anova" class="level1">
<h1>One-Way Anova</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit and print ANOVA for 'hinctnta'</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>model_hinctnta <span class="ot">&lt;-</span> <span class="fu">aov</span>(imwbcnt <span class="sc">~</span> hinctnta, <span class="at">data =</span> dataset)</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>anova_hinctnta <span class="ot">&lt;-</span> <span class="fu">summary</span>(model_hinctnta)</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"imwbcnt - hinctnta</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "imwbcnt - hinctnta\n"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(anova_hinctnta)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Df Sum Sq Mean Sq F value Pr(&gt;F)
hinctnta       1      9   9.330    1.73  0.188
Residuals   2497  13464   5.392               </code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit and print ANOVA for 'happy'</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>model_happy <span class="ot">&lt;-</span> <span class="fu">aov</span>(imwbcnt <span class="sc">~</span> happy, <span class="at">data =</span> dataset)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>anova_happy <span class="ot">&lt;-</span> <span class="fu">summary</span>(model_happy)</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"imwbcnt - happy</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "imwbcnt - happy\n"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(anova_happy)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Df Sum Sq Mean Sq F value Pr(&gt;F)    
happy          1    792   792.1     156 &lt;2e-16 ***
Residuals   2497  12681     5.1                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit and print ANOVA for 'chldhhe'</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>model_chldhhe <span class="ot">&lt;-</span> <span class="fu">aov</span>(imwbcnt <span class="sc">~</span> chldhhe, <span class="at">data =</span> dataset)</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>anova_chldhhe <span class="ot">&lt;-</span> <span class="fu">summary</span>(model_chldhhe)</span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"imwbcnt - chldhhe</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "imwbcnt - chldhhe\n"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(anova_chldhhe)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Df Sum Sq Mean Sq F value Pr(&gt;F)  
chldhhe        1     21  20.594   3.822 0.0507 .
Residuals   2497  13453   5.387                 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit and print ANOVA for 'agea'</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>model_agea <span class="ot">&lt;-</span> <span class="fu">aov</span>(imwbcnt <span class="sc">~</span> agea, <span class="at">data =</span> dataset)</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>anova_agea <span class="ot">&lt;-</span> <span class="fu">summary</span>(model_agea)</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"imwbcnt - agea</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "imwbcnt - agea\n"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(anova_agea)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Df Sum Sq Mean Sq F value   Pr(&gt;F)    
agea           1     79   79.18   14.76 0.000125 ***
Residuals   2497  13394    5.36                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<section id="imwbcnt---hinctnta" class="level3">
<h3 class="anchored" data-anchor-id="imwbcnt---hinctnta">“imwbcnt - hinctnta”:</h3>
<ul>
<li>“Df” represents the degrees of freedom, where 1 refers to the degrees of freedom for the independent variable “hinctnta” and 2497 for the residuals (error).</li>
<li>“Sum Sq” is the sum of squares between groups and residuals.</li>
<li>“Mean Sq” is the mean of squares between groups and residuals.</li>
<li>“F value” is the F-statistic, which measures the variability between group means relative to the variability within groups. It indicates if there is a significant difference between the groups’ means.</li>
<li>“Pr(&gt;F)” is the p-value associated with the F-statistic. It determines the statistical significance of the differences between group means. In this case, the p-value is 0.188, indicating that the relationship between “imwbcnt” and “hinctnta” is not statistically significant.</li>
</ul>
</section>
<section id="imwbcnt---happy" class="level3">
<h3 class="anchored" data-anchor-id="imwbcnt---happy">“imwbcnt - happy”:</h3>
<ul>
<li>Similar to the previous case, this output shows the ANOVA test results for the relationship between “imwbcnt” and “happy.”</li>
<li>The p-value is much smaller (nearly 0), indicating that the relationship between “imwbcnt” and “happy” is statistically significant.</li>
</ul>
</section>
<section id="imwbcnt---chldhhe" class="level3">
<h3 class="anchored" data-anchor-id="imwbcnt---chldhhe">“imwbcnt - chldhhe”:</h3>
<ul>
<li>The ANOVA test is conducted to assess the relationship between “imwbcnt” and “chldhhe.”</li>
<li>The p-value (0.0507) is slightly above the significance level of 0.05, suggesting that the relationship between “imwbcnt” and “chldhhe” may not be statistically significant. <span style="color: red;">We can see that ANOVA shows opposite results comparing to our non-parametric methods</span></li>
</ul>
</section>
<section id="imwbcnt---agea" class="level3">
<h3 class="anchored" data-anchor-id="imwbcnt---agea">“imwbcnt - agea”:</h3>
<ul>
<li>This output represents the ANOVA test results for the relationship between “imwbcnt” and “agea.”</li>
<li>The p-value (0.000125) is much smaller than 0.05, indicating that the relationship between “imwbcnt” and “agea” is statistically significant.</li>
</ul>
</section>
</section>
<section id="nn-anova" class="level1">
<h1>n*n Anova</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>anova_results <span class="ot">&lt;-</span> <span class="fu">aov</span>(imwbcnt <span class="sc">~</span> happy <span class="sc">*</span> chldhhe <span class="sc">*</span> agea <span class="sc">*</span> hinctnta , <span class="at">data =</span> dataset)</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(anova_results)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                              Df Sum Sq Mean Sq F value   Pr(&gt;F)    
happy                          1    792   792.1 158.226  &lt; 2e-16 ***
chldhhe                        1     27    26.8   5.360 0.020681 *  
agea                           1     30    29.6   5.914 0.015089 *  
hinctnta                       1      5     5.4   1.088 0.296958    
happy:chldhhe                  1     13    12.8   2.555 0.110049    
happy:agea                     1      4     3.6   0.722 0.395514    
chldhhe:agea                   1     18    18.4   3.669 0.055533 .  
happy:hinctnta                 1     11    11.0   2.205 0.137714    
chldhhe:hinctnta               1      1     0.6   0.117 0.732082    
agea:hinctnta                  1     52    51.6  10.316 0.001335 ** 
happy:chldhhe:agea             1     65    65.0  12.978 0.000321 ***
happy:chldhhe:hinctnta         1     11    11.0   2.194 0.138667    
happy:agea:hinctnta            1      0     0.3   0.050 0.822927    
chldhhe:agea:hinctnta          1     14    14.5   2.892 0.089148 .  
happy:chldhhe:agea:hinctnta    1      0     0.4   0.075 0.783988    
Residuals                   2483  12430     5.0                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>This multiple-factor ANOVA analysis reveals that “happy,” “chldhhe,” and “agea” have significant individual effects on “imwbcnt.” However, “hinctnta” does not significantly influence “imwbcnt.” Additionally, some interactions between factors are significant, indicating that the combined effects of certain factors are also relevant to “imwbcnt.”</p>
<p><span style="color: red;">We can see that n*n ANOVA shows opposite result comparing to our non-parametric methods regarding the agea</span></p>
</section>
<section id="regression-correlation" class="level1">
<h1>Regression &amp; Correlation</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(imwbcnt <span class="sc">~</span> hinctnta <span class="sc">+</span> agea <span class="sc">+</span> chldhhe <span class="sc">+</span> happy, <span class="at">data =</span> dataset)</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = imwbcnt ~ hinctnta + agea + chldhhe + happy, data = dataset)

Residuals:
    Min      1Q  Median      3Q     Max 
-5.2955 -1.4149  0.1485  1.2859  6.4912 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  2.091398   0.346511   6.036 1.82e-09 ***
hinctnta    -0.020947   0.020187  -1.038   0.2995    
agea        -0.007068   0.002744  -2.575   0.0101 *  
chldhhe      0.109680   0.105965   1.035   0.3007    
happy        0.334785   0.027169  12.322  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.249 on 2494 degrees of freedom
Multiple R-squared:  0.06338,   Adjusted R-squared:  0.06188 
F-statistic: 42.19 on 4 and 2494 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a list of variable combinations</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>variables <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"imwbcnt"</span>, <span class="st">"hinctnta"</span>, <span class="st">"agea"</span>, <span class="st">"chldhhe"</span>, <span class="st">"happy"</span>)</span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Initialize an empty matrix to store the p-values</span></span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>p_values <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="cn">NA</span>, <span class="at">nrow =</span> <span class="fu">length</span>(variables), <span class="at">ncol =</span> <span class="fu">length</span>(variables))</span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(p_values) <span class="ot">&lt;-</span> <span class="fu">colnames</span>(p_values) <span class="ot">&lt;-</span> variables</span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-8"><a href="#cb63-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate p-values for correlation coefficients</span></span>
<span id="cb63-9"><a href="#cb63-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(variables)) {</span>
<span id="cb63-10"><a href="#cb63-10" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (j <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(variables)) {</span>
<span id="cb63-11"><a href="#cb63-11" aria-hidden="true" tabindex="-1"></a>    p_values[i, j] <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(dataset[[variables[i]]], dataset[[variables[j]]])<span class="sc">$</span>p.value</span>
<span id="cb63-12"><a href="#cb63-12" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb63-13"><a href="#cb63-13" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb63-14"><a href="#cb63-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-15"><a href="#cb63-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the p-values matrix</span></span>
<span id="cb63-16"><a href="#cb63-16" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(p_values)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              imwbcnt     hinctnta         agea      chldhhe        happy
imwbcnt  0.000000e+00 1.884854e-01 1.250597e-04 5.068024e-02 9.187245e-35
hinctnta 1.884854e-01 0.000000e+00 7.134959e-13 2.525744e-11 1.433248e-18
agea     1.250597e-04 7.134959e-13 0.000000e+00 1.941357e-78 4.989457e-04
chldhhe  5.068024e-02 2.525744e-11 1.941357e-78 0.000000e+00 2.551993e-01
happy    9.187245e-35 1.433248e-18 4.989457e-04 2.551993e-01 0.000000e+00</code></pre>
</div>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>cor_matrix <span class="ot">&lt;-</span> <span class="fu">cor</span>(dataset[<span class="fu">c</span>(<span class="st">"imwbcnt"</span>, <span class="st">"hinctnta"</span>, <span class="st">"agea"</span>, <span class="st">"chldhhe"</span>, <span class="st">"happy"</span>)])</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cor_matrix)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             imwbcnt    hinctnta        agea     chldhhe       happy
imwbcnt   1.00000000  0.02631533 -0.07666056  0.03909598  0.24246737
hinctnta  0.02631533  1.00000000 -0.14289934 -0.13293774  0.17466424
agea     -0.07666056 -0.14289934  1.00000000 -0.36242789 -0.06959075
chldhhe   0.03909598 -0.13293774 -0.36242789  1.00000000 -0.02276922
happy     0.24246737  0.17466424 -0.06959075 -0.02276922  1.00000000</code></pre>
</div>
</div>
<p>Coefficients:</p>
<p>The intercept represents the expected value of “imwbcnt” when all predictor variables are zero. In this case, when all predictor variables are zero, the estimated value of “imwbcnt” is approximately 2.0914.</p>
<p>hinctnta: The estimated coefficient for “hinctnta” is -0.020947. This means that for a one-unit increase in “hinctnta,” we expect a decrease of approximately 0.020947 units in “imwbcnt,” holding all other predictor variables constant. However, the p-value for this coefficient is 0.2995, which indicates that the relationship between “hinctnta” and “imwbcnt” is not statistically significant at the 0.05 significance level.</p>
<p>agea: The estimated coefficient for “agea” is -0.007068. This means that for a one-unit increase in “agea,” we expect a decrease of approximately 0.007068 units in “imwbcnt,” holding all other predictor variables constant. The p-value for this coefficient is 0.0101, which indicates that the relationship between “agea” and “imwbcnt” is statistically significant at the 0.05 significance level.</p>
<p>chldhhe: The estimated coefficient for “chldhhe” is 0.109680. This means that for a one-unit increase in “chldhhe,” we expect an increase of approximately 0.109680 units in “imwbcnt,” holding all other predictor variables constant. However, the p-value for this coefficient is 0.3007, which indicates that the relationship between “chldhhe” and “imwbcnt” is not statistically significant at the 0.05 significance level.</p>
<p>happy: The estimated coefficient for “happy” is 0.334785. This means that for a one-unit increase in “happy,” we expect an increase of approximately 0.334785 units in “imwbcnt,” holding all other predictor variables constant. The p-value for this coefficient is &lt; 2.2e-16, which indicates that the relationship between “happy” and “imwbcnt” is highly statistically significant.</p>
<p>Residual standard error: The residual standard error is a measure of the average amount by which the observed “imwbcnt” values deviate from the predicted values by the regression model. In this case, the residual standard error is approximately 2.249.</p>
<p>Multiple R-squared and Adjusted R-squared: These values represent the proportion of variance in the response variable “imwbcnt” that can be explained by the predictor variables “hinctnta,” “agea,” “chldhhe,” and “happy.” The multiple R-squared is 0.06338, which means that approximately 6.34% of the variability in “imwbcnt” is explained by the model. The adjusted R-squared (which accounts for the number of predictor variables and the sample size) is 0.06188.</p>
<p>F-statistic and p-value: The F-statistic tests whether there is a significant linear relationship between the predictor variables as a group and the response variable “imwbcnt.” In this case, the F-statistic is 42.19 with a p-value of &lt; 2.2e-16, indicating that there is a significant linear relationship between the predictor variables and “imwbcnt” as a group.</p>
<p>Correlation matrix: The correlation matrix shows the pairwise correlations between the response variable “imwbcnt” and the predictor variables “hinctnta,” “agea,” “chldhhe,” and “happy.” Each cell in the matrix represents the correlation coefficient between two variables. For example, the correlation between “imwbcnt” and “happy” is 0.24246737, indicating a positive correlation between these variables. The diagonal elements of the matrix (top-left to bottom-right) represent the correlations of each variable with itself, and they are all equal to 1.</p>
<p>Overall, the regression analysis suggests that “happy” has a significant positive effect on “imwbcnt,” “agea” has a significant negative effect on “imwbcnt,” while “hinctnta” and “chldhhe” do not have statistically significant effects on “imwbcnt.” The model explains a relatively small proportion of the total variability in “imwbcnt” (6.34%), indicating that other factors not included in the model may also influence “imwbcnt.”</p>
<section id="correlation-heatmap" class="level3">
<h3 class="anchored" data-anchor-id="correlation-heatmap">- Correlation Heatmap</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the correlation heatmap</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a><span class="fu">heatmap</span>(cor_matrix, <span class="at">main =</span> <span class="st">"Correlation Heatmap"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="final_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="discussion" class="level1">
<h1>Discussion</h1>
<section id="h1---people-with-higher-income-levels-hinctnta-are-more-likely-to-believe-that-immigrants-make-the-country-a-better-place-to-live." class="level2">
<h2 class="anchored" data-anchor-id="h1---people-with-higher-income-levels-hinctnta-are-more-likely-to-believe-that-immigrants-make-the-country-a-better-place-to-live.">H1 - People with higher income levels (hinctnta) are more likely to believe that immigrants make the country a better place to live.</h2>
<p>The Wilcoxon rank sum test with continuity correction shows a p-value of 0.003429, indicating that there is a statistically significant difference in beliefs between people with different income levels. However, the Kruskal-Wallis rank sum test does not show a significant overall relationship between “hinctnta” and “imwbcnt.”</p>
</section>
<section id="h2---people-who-report-higher-levels-of-happiness-happy-are-more-likely-to-believe-that-immigrants-make-the-country-a-better-place-to-live." class="level2">
<h2 class="anchored" data-anchor-id="h2---people-who-report-higher-levels-of-happiness-happy-are-more-likely-to-believe-that-immigrants-make-the-country-a-better-place-to-live.">H2 - People who report higher levels of happiness (happy) are more likely to believe that immigrants make the country a better place to live.</h2>
<p>Both the Wilcoxon rank sum test (p-value = 1.671e-12) and the Kruskal-Wallis rank sum test (p-value &lt; 2.2e-16) suggest that there is a significant association between “happy” and “imwbcnt.” This indicates that people who report higher levels of happiness are indeed more likely to believe that immigrants make the country a better place to live.</p>
</section>
<section id="h3---people-with-children-chldhhe-are-more-likely-to-believe-that-immigrants-make-the-country-a-better-place-to-live." class="level2">
<h2 class="anchored" data-anchor-id="h3---people-with-children-chldhhe-are-more-likely-to-believe-that-immigrants-make-the-country-a-better-place-to-live.">H3 - People with children (chldhhe) are more likely to believe that immigrants make the country a better place to live.</h2>
<p>The Wilcoxon rank sum test with continuity correction shows a p-value of 0.0507, suggesting that there is a weak statistical significance in the difference in beliefs between people with and without children. However, the Kruskal-Wallis rank sum test does not indicate a significant overall relationship between “chldhhe” and “imwbcnt.”</p>
</section>
<section id="h4---younger-people-age-are-more-likely-to-believe-that-immigrants-make-the-country-a-better-place-to-live." class="level2">
<h2 class="anchored" data-anchor-id="h4---younger-people-age-are-more-likely-to-believe-that-immigrants-make-the-country-a-better-place-to-live.">H4 - Younger people (age) are more likely to believe that immigrants make the country a better place to live.</h2>
<p>The Kruskal-Wallis rank sum test shows a p-value of 0.0273, indicating that there is a statistically significant association between “agea” and “imwbcnt.” This suggests that younger people are more likely to believe that immigrants make the country a better place to live.</p>
</section>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>Overall, the results provide mixed support for the hypotheses. Higher levels of happiness (happy) and younger age (agea) are both positively associated with the belief that immigrants make the country a better place to live. However, the relationship between income (hinctnta) and belief in immigrant impact is not as clear-cut and may require further investigation. Similarly, while there is a weak indication of an association between having children (chldhhe) and belief in immigrant impact, it is not strongly supported.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>
